[options]
admin_passwd = $pbkdf2-sha512$600000$n7OWcm7N2fv//18rJUTo/Q$AdjQLmGI8dm.laYN7BUpwoN.YIORZDsixdAQLPb0A0VQp0BdTQNZYZKyMBIwFRtPSOB6li3uoR44zT.3y97i6Q
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /Users/chirags-mac/Documents/SDLC_Internship/Task1/odoo/odoo/addons,/Users/chirags-mac/Documents/SDLC_Internship/Task1/odoo/addons,/Users/chirags-mac/Documents/SDLC_Internship/Task1/custom_addons

